x-common-variables: &common-variables
  PYTHONUNBUFFERED: 1
  POSTGRES_USER: postgres
  POSTGRES_DATABASE: postgres
  POSTGRES_PASSWORD: admin
  REDIS_HOST: cache
  REDIS_PORT: 6379
  SUPERADMIN_PASSWORD: admin123
  JWT_SECRET: secret
  JWT_ALGORITHM: HS256
  ELASTICSEARCH_HOST: elasticsearch
  ELASTICSEARCH_PORT: 9200
  DISTRIBUTION_HOST: distribution
  DISTRIBUTION_PORT: 5000
  PEM_CERT_PATH: /code/certs/cert.pem

services:
  backend:
    build: ./server
    image: magley/mocker-hub-backend:latest
    ports:
      - "8000:8000"
    expose:
      - "8000"
    depends_on:
      - db
      - cache
      # - nginx
      - elasticsearch
      - distribution
      - log_collector
      - worker
    environment:
      <<: *common-variables

      # To run tests, do `RUN_TESTS=true docker compose up`.
      # However, I've been having issues with this on WSL,
      # so instead I've created an `.env` in project root
      # with RUN_TESTS=true.
      RUN_TESTS: ${RUN_TESTS:-false}
    restart: on-failure
    
    develop:
      watch:
        - action: sync
          path: ./
          target: /code
    
    volumes:
      - backend_cfg:/code/volume-server-cfg/
      - ./images:/code/images
      - ./distribution/certs:/code/certs
      - ./logs:/code/logs

  db:
    image: postgres:15.9-alpine3.20
    restart: always
    shm_size: 128mb
    ports:
      - "8001:5432"
    environment:
      # POSTGRES_USER: postgres
      # POSTGRES_DATABASE: postgres
      POSTGRES_PASSWORD: admin

  db_adminer:
    # Login form data:
    # --------------------------------
    # Database:     PostgreSQL
    # Server:       db
    # Username:     POSTGRES_USER
    # Password:     POSTGRES_PASSWORD
    # Database:     POSTGRES_DATABASE
    #
    image: adminer:4.8.0-standalone
    restart: always
    ports:
      - "8002:8080"

  nginx:  # And frontend.
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
  
  cache:
    image: redis:alpine3.20
    restart: always
    ports:
      - '6888:6379'
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 5s
      timeout: 3s
      retries: 5
    # volumes: 
    #   - cache:/data
    
  worker:
    image: magley/mocker-hub-backend:latest
    restart: always
    environment:
      REDIS_SCHEME: redis 
      PYTHONPATH: /code
      <<: *common-variables
    entrypoint: []
    command: ["python", "-m", "app.api.config.worker"]
    depends_on:
      - db
      - cache
      - distribution
    volumes:
      - backend_cfg:/code/volume-server-cfg/
      - ./images:/code/images
      - ./distribution/certs:/code/certs
      - ./logs:/code/logs

  rq_dashboard:
    image: eoranged/rq-dashboard:v0.6.3
    ports:
      - "9181:9181"
    environment:
      RQ_DASHBOARD_REDIS_URL: redis://cache:6379
    depends_on:
      - cache

  distribution:
    image: "registry:2" 
    ports:
      - "5000:5000"
    volumes:
      - "./distribution/config.yaml:/etc/docker/registry/config.yml"
      - "./distribution/certs:/mnt/local/certs"
      - "./distribution/entrypoint.sh:/entrypoint.sh"
    entrypoint: ["/bin/sh", "/entrypoint.sh"]
    environment:
      RUN_REGISTRY_GC: "true"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.6.2
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms256m -Xmx256m  # In case we run out of memory, change 256m to 512m or 1g
      - ELASTIC_PASSWORD=1234
      - xpack.security.enabled=false
      - xpack.ml.enabled=false
    ports:
      - 9200:9200
      - 9300:9300
    # I've added these lines below to speed up the booting of ES. In case something goes wrong, comment them out.
    volumes:
    - /tmp/elasticsearch/data
    ulimits:
      memlock:
        soft: -1
        hard: -1

  log_collector:
    build: ./log_collector
    restart: on-failure
    volumes:
      - ./logs:/logs
    environment:
      - ES_HOST=elasticsearch:9200
    depends_on:
      - elasticsearch

volumes:
  backend_cfg:
    driver: local
    driver_opts:
      type: none
      device: ./volume-server-cfg
      o: bind
