services:
  backend:
    build: ./server
    ports:
      - "8000:8000"
    expose:
      - "8000"
    depends_on:
      - db
    environment:
      PYTHONUNBUFFERED: 1
    restart: always
    
    develop:
      watch:
        - action: sync
          path: ./
          target: /code