name: Run Unit & Integration Tests

on:
  pull_request:
    branches:
      - develop

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout to branch
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10.15'

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r server/requirements.txt

    - name: Run the tests
      env:
        mocker_hub_TEST_ENV: 1
      run: |
        pytest server/app/tests/