name: Run Tests And Deploy Application To A Docker Registry

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout to branch
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10.15'

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r server/requirements.txt

    - name: Run the tests
      env:
        mocker_hub_TEST_ENV: 1
      run: |
        pytest server/app/tests/

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Deploy image to Docker Hub
      if: success()
      run: |
        docker-compose -f compose.yaml build
        docker-compose -f compose.yaml push